### ISSUE TITLE
Server-side sorting todo

### ISSUE THREAD

**Issue by Donkie** [Donkie/Spoolman#98]
- [ ] Allow multiple filament name filter selects
- [ ] Filter by empty
- [ ] remaining_weight sort
- [ ] Filter by multiple materials etc
- [ ] Don't load materials etc so often
- [ ] Contract tests
